{"17dea226910a2c9af2c0541948ded656":{"statistic":{"failed":1,"broken":0,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"e26b424934c00cef","status":"failed","statusDetails":"The following error originated from your application code, not from Cypress.\n\n  > expected 'This user already exist.' to equal 'Sign up successful.'\n\nWhen Cypress detects uncaught errors originating from your application it will automatically fail the current test.\n\nThis behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.\n\nhttps://on.cypress.io/uncaught-exception-from-application","time":{"start":1719362716593,"stop":1719362719141,"duration":2548}}]}}